
START_SYMBOL = "<s>"
END_SYMBOL = "</s>"
UNKNOWN_SYMBOL = "<UNK>"
UNKNOWN_VERB_SYMBOL = "<UNKVERB>"
UNKNOWN_NOUN_SYMBOL = "<UNKNOUN>"
UNKNOWN_ADJ_SYMBOL = "<UNKADJ>"
UNKNOWN_ADV_SYMBOL = "<UNKADV>"
UNKNOWN_PREP_SYMBOL = "<UNKPREP>"

